{{- include "banking-application.validateValues" . -}}
{{- if .Values.serviceAccount.create }}
# =============================================================================
# ServiceAccount
# =============================================================================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "banking-application.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "banking-application.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.workloadIdentity.enabled }}
    azure.workload.identity/client-id: {{ .Values.workloadIdentity.clientId | quote }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: false
{{- end }}
