{{- if .Values.podDisruptionBudget.enabled }}
# Pod Disruption Budget: protects availability during voluntary disruptions such
# as node upgrades and cluster autoscaler drains.

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "banking-application.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "banking-application.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "banking-application.selectorLabels" . | nindent 6 }}
{{- end }}
